---
title: "Assignment-2 : ODD Assignment"
author: "Leyla Yigit"
date: "31 Ekim 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#Insntal the package if you already haven't

# Load the package to the session
library(tidyverse)
library(readxl)
#install.packages("magrittr") library(magrittr)
dd <- "plyr"
install.packages(dd)



# install.packages("devtools")
#devtools::install_github("tidyverse/readxl")
#install.packages("tidyverse", repos = "https://cran.r-project.org")
# Set your working directory (the directory which you keep
"library function takes package name as first argument. This name actually refers to the name passed as package argument 
rather than any value associated to that name. 
library function internally converts the package argument to a character literal (except when character.only is set to TRUE).
So,

plyr <- dplyr()
library(plyr)
will undergo

if(!character.only
  package <- as.character(substitute(plyr))"
```




```{r cars}
summary(cars)
```

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
